project:
  type: website
  output-dir: docs # Output directory for GitHub Pages
  render:
    - "cv_en.qmd" # Explicitly render cv_en.qmd
    - "cv_hu.qmd" # Explicitly render cv_hu.qmd
  post-render:
    - cp docs/cv_en.html docs/index.html

website:
  page-footer:
    border: true
    background: dark
  navbar:
    left:
      - text: "🇬🇧 Curriculum Vitae in English"
        href: index.html # Link to the CV webpage
      - text: "🇭🇺 Curriculum Vitae in Hunagrian"
        href: cv_hu.html # Link to the CV webpage

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    link-external-newwindow: true
    canonical-url: https://barizona.github.io/cv/ # Set your GitHub Pages URL
    toc: true          # Enable Table of Contents for HTML
    toc-depth: 2       # Optional: Set depth of TOC (e.g., 2 for h1 and h2)
  pdf:
    # mainfont: Proxima Nova
    keep-tex: false # Optional: Keeps intermediate .tex for debugging
    linkcolor: "RoyalBlue"
    urlcolor: "RoyalBlue"
  docx:
    keep-tex: false # Optional: Keeps intermediate .tex for debugging

resources:
  - CNAME # Include if you have a custom domain (optional)
