project:
  type: website
  output-dir: docs # Output directory for GitHub Pages
  render:
    - "cv.qmd" # Explicitly render cv.qmd

website:
  page-footer:
    border: true
    background: dark
    center:
      - text: "<b>Download PDF</b>"
        href: cv.pdf # Link to the PDF version of the CV
  navbar:
    left:
      - text: "Curriculum Vitae in English"
        href: index.html # Link to the CV webpage
      - text: "Curriculum Vitae in Hunagrian"
        href: index.html # Link to the CV webpage

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    link-external-newwindow: true
    canonical-url: https://barizona.github.io/cv/ # Set your GitHub Pages URL
  pdf:
    extension: classic-cv # Use the classic-cv extension for PDF rendering
    keep-tex: false # Optional: Keeps intermediate .tex for debugging

resources:
  - CNAME # Include if you have a custom domain (optional)
